# Generated by Django 4.2 on 2023-04-14 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('instructions', models.TextField()),
                ('thumbnail', models.URLField()),
                ('cook_time', models.DurationField()),
                ('prep_time', models.DurationField()),
                ('total_time', models.DurationField()),
                ('serving_size', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ingredients', models.ManyToManyField(to='nomnom.ingredientline')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientline',
            name='found_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomnom.recipe'),
        ),
    ]
