# Generated by Django 4.2 on 2023-04-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomnom', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientline',
            name='quantity',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
